# Generated by Django 6.0.3 on 2026-05-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='value',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='value',
            field=models.SmallIntegerField(default=1),
        ),
    ]
